# ANOVA

**Caution: in a highly developmental stage! See Section  \@ref(caution).**

(From 2018-2019 DSCI 561 lab1)

Remember that to make a hypothesis test, we need to first come up with some "distance metric" (called the test statistic) to measure discrepency from the null hypothesis. For example, to test whether two groups have different population means, a t-test bases its distance metric / test statistic on the difference between the two sample means -- the further this metric is from 0, the more evidence we have that the null hypothesis is not true.

There's another way to measure discrepency from the null hypothesis that all group means are equal -- a way that allows for any number of groups to be compared all at once (not just two). But, it operates under the assumption that the variance of the data in each group is the same. Here's the idea. If the population means of each group truly are the same, then we can estimate that common variance in two ways: using the "overall" variance (ignoring the groups altogether), OR by averaging the variances of each group. The distance metric / test statistic is based off of the ratio of these two values (which is more meaningful than looking at the difference between the two).

This is ANOVA -- ANalysis Of VAriance.

For the pregnancy (two-group) dataset, calculate:

1. the overall variance of the response, and store it in var_tot;
2. the average of the variances for each group, and store it in var_grp; and
3. how many times larger is (1) compared to (2)? i.e., calculate (1)/(2). Store it in my_ratio.

Take a moment to reflect as to whether you think this is a big difference or not (no need to write anything).

The actual test statistic of ANOVA has minor adjustments to the ratio you just calculated, although is based on the same concepts.

- Since (1) >= (2), the ratio will always be >1. So instead, the numerator is based on the difference between (1) and (2) (this results in a variance sometimes called the "treatment variance").
- The variance estimates don't always use n-1 -- they adjust for the number of groups, based on the concept of "degrees of freedom".

Still, the larger the ratio (test statistic), the less evidence we have to support the null hypothesis.

Your task: run the ANOVA in R using the aov() function for the pregnancy data. Quality code uses broom::tidy(). Then, store the p-value in preg_aov_p, the test statistic in preg_aov_F, and the "Species" and "Residuals" degrees of freedom (df) as a length-2 vector in the variable preg_aov_df.

If the null hypothesis is true, then the sampling distribution of this test statistic is (to a good approximation) a specific F-distribution. This "good approximation" is thanks to the CLT, and is true as long as the sample size isn't small (and it's always true if the data are Gaussian).
