# Robust Regression in R

**Caution: in a highly developmental stage! See Section  \@ref(caution).**

DSCI 562 Lab 4 Tutorial

There are many R packages out there to assist with robust estimation. It depends on the task at hand. We'll go over a few.

For robust linear regression, there are a few options. 

There's the `rlm` function in the `MASS` package. It works in a similar way as the `lm` function. Can also use the functions `predict`, `residuals`, `coefficients`, etc. on the output. I like this option because it allows for different psi functions besides the Huber.

```
library(MASS)
(fit6 <- rlm(mpg ~ disp + wt, data=mtcars))
(fit7 <- rlm(mpg ~ disp + wt, data=mtcars, psi=psi.bisquare))
```

The package `robustbase` has the function `lmrob` for linear models, but also has `glmrob` for GLM's. Similarly, the `robust` package has similar functions `lmRob` and `glmRob`. 

A robust version of GAM's can be obtained with the `robustgam` function in the `robustgam` package. 

A robust version of LME's can be obtained with the `rlmer` function in the `robustlmm` package. 

### Heavy Tailed Regression

For a heavy tailed extension of `lm`, one can use the `tlm` function in the `hett` package. The package `heavy` has some regression techniques using heavy tailed distributions. 
