# reference-treatment parameterization

(From DSCI 561 lab1, 2018-2019)

When data fall into groups, you already know how to estimate the population mean for each group: calculate the sample mean of the data in each group. For example, the mean Sepal.Width of the three species in the iris dataset are:

```
iris %>% 
    group_by(Species) %>% 
    summarize(mean_sepal_width = mean(Sepal.Width))
```

In this exercise, you'll start exploring a "trick" that linear regression models use so that we can obtain the same mean estimates by evaluating a line. Although it might seem silly to do, especially when we can just do a group_by() and summarize(), using this trick will be very important when we start incorporating more variables in our model, as we'll soon see in this course.

Next, using the "trick" that linear regression models use, you'll write these estimates as a line, so that we can obtain the mean estimates by evaluating the line. Here's the trick: convert the categories to a numeric variable, where one category takes the value 0, and the other takes the value 1.

Let's convert "first" to 0, and "other" to 1:

```
x_map <- c(first=0, other=1)
preg <- mutate(preg, num_x = x_map[birth_order])
head(preg)
```

What's the equation of the line that goes through the mean estimates of both groups? Specify this by storing the slope and (y-) intercept of the line in the variables preg_slope and preg_int, respectively. This line is called the regression line.

In Inf-1 lab3, you made a plot of the data, including the two means with a confidence interval. Here's the code (using asymptotics to form the CI), zooming in on the "center" of the data (uncomment preg_plot to view the plot):

```
preg_plot <- preg %>%
    group_by(birth_order, num_x) %>%
    summarize(mean = mean(prglngth),
              n    = length(prglngth),
              se   = sd(prglngth) / sqrt(n)) %>%
    ggplot(aes(x = num_x)) +
    geom_violin(data    = preg,
                mapping = aes(y = prglngth, group = birth_order), 
                adjust  = 5) +
    geom_point(aes(y = mean), colour = "red") +
    geom_errorbar(aes(ymin = mean + qnorm(alpha/2)*se,
                      ymax = mean - qnorm(alpha/2)*se),
                  colour = "red",
                  width  = 0.2) +
    theme_bw() +
    labs(x = "Birth Order", 
         y = "Pregnancy Length (weeks)") +
    ylim(c(30, 50)) +
    scale_x_continuous(breaks = enframe(x_map)$value, 
                       labels = enframe(x_map)$name)
```

Add the line to this plot.

Can we always draw a straight line through the means of two groups? Why or why not?

In this lab, we won't be exploring the trick that linear regression models use when we have multiple groups. But, you'll explore what we can't do.

For each species in the iris (three-group) data set, the code below:

calculates the mean sepal width in the column mean_sepwid, along with the standard error of the mean in the se column, placed in the data frame iris_est.
plots the raw data with a violin+jitter plot, stored in the variable iris_plot (uncomment it to view it).

```
(iris_est <- iris %>% 
    group_by(Species) %>% 
    summarize(
        mean_sepwid = mean(Sepal.Width),
        se          = sd(Sepal.Width)/sqrt(length(Sepal.Width))
    ))
iris_plot <- iris %>% 
    mutate(Species = fct_reorder(Species, Sepal.Width)) %>% 
    ggplot(aes(Species)) +
    geom_violin(aes(y = Sepal.Width)) +
    geom_jitter(aes(y = Sepal.Width), 
                alpha=0.2, width=0.1, size=0.5) +
    theme_bw() +
    labs(x = "Species", 
         y = "Sepal Width")
iris_plot
```

Your task is to add the group means and confidence intervals to the plot. You can do this by adding layers to iris_plot. You can use asymptotic theory to calculate the confidence intervals, calculated by:

$$\bar{x} \pm z_{\alpha/2} \text{SE}.$$

Can we fit a single straight line through the mean sepal widths across the three species groups? Why or why not?

## More than one category (Lab 2)

In class, we saw two "ways to store information" about groups means -- in technical terms, two parameterizations.

The first and most "direct" parameterization is cell-wise parameterization, a fancy way of saying that we're just going to consider the raw means themselves: one mean for each group. For the three species in the iris dataset, here are estimates of these parameters:

In [ ]:
iris %>% 
	group_by(Species) %>% 
	summarize(mean_sepal_width = mean(Sepal.Width))
The mean of the response (conditional on species) can be written as a linear model, if we call the above means $\mu_0,\mu_1,\mu_2$ (respectively), and define the following three predictors:

$$X_0 = 1 \text{ if setosa, } 0 \text{ otherwise},$$$$X_1 = 1 \text{ if versicolor, } 0 \text{ otherwise},$$$$X_2 = 1 \text{ if virginica, } 0 \text{ otherwise}.$$
Then, the linear model is

$$E(\text{Sepal Width} \mid \text{species}) = \mu_0 X_0 + \mu_1 X_1 + \mu_2 X_2.$$
In this exercise, you'll be exploring another parameterization that's useful in linear regression: the reference-treatment parameterization.

1.1
rubric={autograde:3}

To keep things different from lm(), let's consider the virginica species as our "reference". The reference-treatment parameterization is then: $$\theta=\mu_{\text{virginica}},$$$$\tau_1=\mu_{\text{versicolor}}-\theta,$$$$\tau_2=\mu_{\text{setosa}}-\theta,$$ where $\mu$ denotes the mean of that species' sepal width.

Your task: Calculate estimates of these parameters, and store the estimates in the (respective) variables theta, tau1, and tau2.

In [ ]:
# Calculate theta, tau1, and tau2
# your code here
fail() # No Answer - remove if you provide an answer
print(theta)
print(tau1)
print(tau2)


Provide an interpretation for $\theta$, $\tau_1$, and $\tau_2$. One brief sentence for each is enough.

Let's now write this information as a single (linear) equation containing:

two predictors $X_1$ and $X_2$, and
the parameters $\theta$, $\tau_1$, and $\tau_2$.
Let's focus on the predictors first. Define: $$X_1 = 1 \text{ if versicolor, } 0 \text{ otherwise},$$$$X_2 = 1 \text{ if setosa, } 0 \text{ otherwise}.$$ We've deliberately not defined a predictor for virginica, the reference group.

Your task: What are the values of $X_1$ and $X_2$ for each species? Store the values in three length-2 vectors called x_setosa, x_versicolor, and x_virginica.

Use the predictors $X_1$ and $X_2$, along with the parameters $\theta$, $\tau_1$, and $\tau_2$, to write a linear equation that returns the species mean $\mu$. The equation should look like: $$E(Y \mid \text{species}) = (1) + (2)\times(3) + (4)\times(5)$$ To use the autograder for this question, specify the order that $X_1$, $X_2$, $\theta$, $\tau_1$, and $\tau_2$ are to appear in the equation, respectively, in a vector containing the numbers 1 through 5, named eq_order.

For example, specifying eq_order <- c(1,2,3,4,5) corresponds to the equation $E(Y \mid \text{species}) = X_1 + X_2  \theta + \tau_1  \tau_2$ (which is not the correct equation)

(Based on your answers to 1.4 and 1.5, can you see why the parameter that goes in place of (1) is also called the "intercept"?)

Now try using lm(): use the iris data with the same predictor and response (don't include -1 in the formula, so that you end up with a reference-treatment parameterization).

Your task: What's the reference species? Put the name of the species as a character in the variable iris_lm_ref_species.