# Linear models in general

**Caution: in a highly developmental stage! See Section  \@ref(caution).**

(DSCI 561 lab 2, 2018-2019)

In general, linear models estimate the mean using $p$ predictors $X_1, \ldots, X_p$ (this time, the subscripts denote "predictor number" instead of "observation number", and the vectors $\boldsymbol{X}$ and $\boldsymbol{x}$ contain the predictors, not the observations), according to the following generic equation: $$E(Y \mid \boldsymbol{X}=\boldsymbol{x}) = \beta_0 + \beta_1 x_1 + \cdots + \beta_p x_p.$$ We saw that:

a $K$-level categorical predictor enters the equation through $K-1$ binary predictors (relative to a "baseline" category), and
a numeric predictor enters the equation as itself.
We will now consider using both sepal length (numeric) and species (categorical) as predictors of sepal width.

6.1

Fit a linear regression line to sepal length ($X$) vs. sepal width ($Y$) for each species independently. Plot the results by facetting by species.

Note that all we're looking for here is the plot. You can bypass the lm() calls by adding the layer geom_smooth(method="lm", se=FALSE), which runs the linear regression separately in each panel.



Although these look like three separate models, it's still just one model: one specification as to how to estimate the mean. We can write a single equation that describes this specification, using the following variables: $$X_1 = \text{sepal length}$$$$X_2 = 1 \text{ if versicolor, } 0, \text{ otherwise}$$$$X_3 = 1 \text{ if virginica, } 0, \text{ otherwise}$$$$X_4 = X_2 X_1$$$$X_5 = X_3 X_1$$ The model becomes: $$E(Y \mid \boldsymbol{X} = \boldsymbol{x}) = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3 + \beta_4 X_4 + \beta_5 X_5 $$

Your task: specify the slope and intercept of the regression lines for each species, in terms of the $X$'s and $\beta$'s above. We've given you the answer for Setosa already. Answer by copying and pasting the below table into the answer cell, and filling in the missing table cells.

Hint: evaluate whatever $X$'s you can.

Species	Intercept	Slope
Setosa	$\beta_0$	$\beta_1$
Versicolor		
Virginica		
YOUR ANSWER HERE

6.3

$X_4$ and $X_5$ are called interaction terms, and are not present by default in the lm() function. In their absence, what are the slopes and intercepts of the regression line for each species? Answer like you did above, in terms of the $X$'s and $\beta$'s, by filling in the below table. We've given you the answer for Setosa already.

Species	Intercept	Slope
Setosa	$\beta_0$	$\beta_1$
Versicolor		
Virginica		
YOUR ANSWER HERE

6.4

Make a similar plot as in Exercise 6.1, but for the model without interaction.
